project:
  type: website
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "TOPSTSCHOOL"
  site-url: https://ciesin-geospatial.github.io/TOPSTSCHOOL/
  favicon: images/TOPSTSCHOOL-updated-logo02.png  
  
  page-footer: 
    right: "This page is built with ❤️ help from [NASA Openscapes](https://nasa-openscapes.github.io/), and [Quarto](https://quarto.org/), with theme from [vetiver](https://github.com/rstudio/vetiver.rstudio.com)"
    left: "&copy; CC-By TOPSTSCHOOL Development Team"
 
  navbar:
    logo: images/TOPTSCHOOL-logo02.hi-res.png
    href: https://ciesin-geospatial.github.io/TOPSTSCHOOL/
    right:
    # - text: "Home"
    #   href: index.html
    - text: "About"
      href: about.qmd
    - text: "Get Involved"
      href: get-involved.qmd
    - text: "SCHOOL Yearbook"
      href: dev-team.qmd 
    - text: "Modules"
      href: modules.qmd
    - icon: github
      href: https://github.com/ciesin-geospatial/TOPSTSCHOOL
    - icon: youtube
      href: https://www.youtube.com/channel/UCOIrczFd7_ht2bNUQ3qnM8w
  sidebar:
      title: "TOPSTSCHOOL"
      logo: images/TOPSTSCHOOL-updated-logo02.png
      pinned: false
      align: center
      tools: 
        - icon: globe
          href: https://ciesin-geospatial.github.io/TOPSTSCHOOL/
          text: "TOPSTSCHOOL GitHub io"
        - icon: github
          href: https://github.com/ciesin-geospatial/TOPSTSCHOOL
          text: "TOPSTSCHOOL GitHub repo"
format:
  html:
    embed-resources: true
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left




# old _site.yml content below for comparison while converting to Quarto
#
# name: "."
# title: "NASA-Openscapes"
# description: |
#   NASA-Openscapes
# favicon: images/openscapes_hex.png  
# output_dir: "docs"
# navbar:
#   logo: images/openscapes_hex.png
#   href: https://openscapes.org
#   right:
#     - text: "Home"
#       href: index.html
#     - text: "About"
#       href: about.html
#     - text: "Mentors"
#       href: mentors.html
#     - text: "Champions"
#       href: champions.html 
#     - text: "Tutorials"
#       href: tutorials.html 
#     - text: "Events"
#       href: events.html
#     - icon: fab fa-twitter
#       href: https://twitter.com/openscapes
#     - icon: fab fa-github
#       href: https://github.com/nasa-openscapes
# output: distill::distill_article
# theme: theme.css
