---
title: "Join the NASA TOPSTSCHOOL Team"
description: |
  Learn how to join the SCHOOL Project. 
---

## Subject Matter Experts 

We are looking for **researchers** to join as **Subject Matter Experts (SMEs)** on our SCHOOL project advisory committee for one module. 
Your expertise is vital in developing learning modules applying Open Science principles to the module topics. Researchers will engage in workshops and short sprints in a hybrid, open-meeting format.

The SCHOOL Project aims to empower students to apply Open Science principles to thematic areas, including Water, Health and Air Quality, Environmental Justice, Disasters, Wildfires, Agriculture, and Climate. We're particularly interested in team members passionate about inclusive pedagogy. 
To **join as a Subject Matter Expert** or **learn more**, please fill out the [SME Google Form](https://forms.gle/USbE8itQpQ4A67AM7) or contact us at **TOPSTSCHOOL@ciesin.columbia.edu**.

## Open Science Team

We are looking for **participants** to join the **Open Science Team** to give input on the **development of learning modules**. 
Participants will engage in workshops and short sprints in a hybrid, open-meeting format. Our workshop focuses on FAIR and CARE principles in learning, making us particularly interested in team members with a passion for inclusive pedagogy. Following the launch workshop, participants will be asked for feedback during two 1-hour remote participation meetings. 
To **join the Open Science Team** or **learn more**, please fill out the [Participant Google Form](https://forms.gle/U8ZEfbE14uhBjTZDA) or contact us at **TOPSTSCHOOL@ciesin.columbia.edu**.



## Fall 2023: Mentors give workshops at AGU

December 11 - 15, NASA Openscapes Mentors will attend the AGU annual meeting and deliver workshops. High-level planning happens in the [2023-planning-agu](https://github.com/NASA-Openscapes/2023-planning-agu) GitHub repo.

## Water Resources SCHOOL Workshop - [I-GUIDE Forum 2023](https://iguide.illinois.edu/forum-2023/agenda-of-i-guide-forum-2023/)

October 4-5, TOPSTSCHOOL Development Team will host a workshop at the I-GUIDE Fourm 2023. ScienceCore Heuristics for Open Science Outcomes in Learning (SCHOOL): Water Resources Module Development.


