---
title: "test3"
author: "test3"
date: "2023-11-27"
output: html_document
---
```{r}
library(httr)
library(raster)
```




```{r}
#netrc_path <- "~/NRT_flood/.netrc"
cookie_path <- "~/NRT_flood/.urs_cookies"
downloaded_file_path <- "~/NRT_flood/filename.tif"
```


```{r}

# Create the .netrc content in memory
#netrc_content <- sprintf("machine urs.earthdata.nasa.gov login %s password %s",getPass("Enter your username: "), getPass("Enter your password: "))


# Create a temporary file in memory
temp_netrc <- tempfile(fileext = ".netrc")

# Write the .netrc content to the temporary file
writeLines(sprintf("machine urs.earthdata.nasa.gov login %s password %s", getPass("Enter your username: "), getPass("Enter your password: ")), temp_netrc)

# Set the NETRC environment variable to the temporary file path
Sys.setenv(NETRC = temp_netrc)

# Your download code here
netrc_path <- temp_netrc
```

```{r setup, include=FALSE}
set_config(config(followlocation=1,netrc=1,netrc_file=netrc_path,cookie=cookie_path,cookiefile=cookie_path,cookiejar=cookie_path))

```

```{r}
#content1 <- content(GET(url = "https://nrt3.modaps.eosdis.nasa.gov/api/v2/content/archives/allData/61/MCDWD_L3_F3_NRT/2023/324/MCDWD_L3_F3_NRT.A2023324.h00v02.061.tif"))
tif_content <- raster::raster(httr::content(response, "raw"))
```
```{r}
response <- httr::GET(url = "https://nrt3.modaps.eosdis.nasa.gov/api/v2/content/archives/allData/61/MCDWD_L3_F3_NRT/2023/324/MCDWD_L3_F3_NRT.A2023324.h09v06.061.tif")
```
```{r}
tif_content <- raster::raster("https://nrt3.modaps.eosdis.nasa.gov/api/v2/content/archives/allData/61/MCDWD_L3_F3_NRT/2023/324/MCDWD_L3_F3_NRT.A2023324.h09v06.061.tif")
```

```{r}
print(tif_content)
```
```{r}
plot(tif_content, main = "Your Raster Layer Title", col = terrain.colors(20))
```


```{r}
raster_data <- raster(tif_content)
plot(raster_data)
```

